### ISSUE TITLE
We can't get our products 

### ISSUE THREAD

**Issue by bankai14** [intershop/intershop-pwa#1160]
**Actual Behavior**

We have an important bug concerning the display of products, according to the documentation it is enough to do in URI:

"/products"

Documentation : https://support.intershop.com/kb/index.php/Display/251S57

When we do it on our domain we have the following message :

"Internal Server Error"

How to get our products please?

**Expected Behavior**

For example in the demo the products are retrieved:

https://intershoppwa.azurewebsites.net/INTERSHOP/rest/WFS/inSPIRED-inTRONICS_Business-Site/rest;loc=fr_FR;cur=EUR/products

We want to have an equivalent result.

**Steps to Reproduce the Bug**

1. Go to https://int-edit-ish24-trnsz.fse.intershop.de//INTERSHOP/rest/WFS/inSPIRED-inTRONICS_Business-Site/rest;loc=fr_FR;cur=EUR/products
2. See error: "Internal Server Error"

[AB#76614](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/76614)

**Comment by shauke** [comment]
I would say this is not the right place for such an issue since it is not a problem of the PWA but a problem with the Intershop Commerce Management REST API. As long as the REST API is not responding the PWA cannot do much about it.
Having no access to the backend I would assume rebuilding the search index might be a fist start to resolve the issue.
