### ISSUE TITLE
Icons are missing when clicking on “add address” button in my account page

### ISSUE THREAD

**Issue by schadii** [intershop/intershop-pwa#1352]
**Actual Behavior**

Currently, if click on “Add Address” in my account page, icons are disappearing in the preferred Invoice address, shipping address and Further Address.

**Expected Behavior**

By clicking on “Add address” the blank form will expand and below the form, both pencil and trash icons will be shown in the further address. In addition, an edit icon should be displayed next to the preferred invoice address and the shipping address.

**Steps to Reproduce the Bug**

1. Go to Addresses in my account page.
2. Click on 'Add Address' button
3. Scroll down to 'preferred Invoice address, shipping address and 
Further Address.'

**Environment Details**

Browser: Chrome

<img width="501" alt="My account-Add Address" src="https://user-images.githubusercontent.com/105789331/211537809-98e4a87e-8044-4c3a-91e5-284f4c74ab32.png">

[AB#82436](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82436)

**Comment by SGrueber** [comment]
We implemented the current behavior intentionally. If the user wants to add an address all other action buttons disappear to reduce potential errors on page. It is like opening a form in a dialog, so the user can only interact with the dialog but not with the page any more.
I`d suggest to leave the behavior as it is otherwise feel free to open the ticket again.
