### ISSUE TITLE
Switch language after accepting cookies

### ISSUE THREAD

**Issue by ximfritz** [intershop/intershop-pwa#1489]
**Actual Behavior**
1. Open https://intershoppwa.azurewebsites.net/home 
2. Switch language to DE
3. Site switched to DE
4. Accept all cookies
5. Site switches to EN

**Expected Behavior**

1. Open https://intershoppwa.azurewebsites.net/home 
2. Switch language to DE
3. Site switched to DE
4. Accept all cookies
5. Site stays on DE

**Steps to Reproduce the Bug**

Take a look at actual behavior

**Environment Details**

- Desktop: \*

  - Browser [Firefox](url)
  - Project Code Version

- Smartphone: \*
  - Browser [e.g. stock browser, safari], Version [e.g. 22]
  - Project Code Version

**Additional Context, like Screenshots, Log File Snippets etc.**

Video of the problem

https://github.com/intershop/intershop-pwa/assets/121181702/4d6540c2-c207-40f7-8f2c-80308ecb7bbe

[AB#88811](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88811)

**Comment by Eisie96** [comment]
This problem is known. With `ng serve` the language can only be set via an url parameter. When the page should be reloaded, the language parameter has been disappeared and the default language is used again.

To avoid the problem a MULTI_CHANNEL configuration can be applied. With that it is possible to add the language information to the url path.

e.g. 

```yaml
MULTI_CHANNEL: |
        .+:
          - baseHref: /en
            channel: default
            lang: en_US
```

There is an open PR (https://github.com/intershop/intershop-pwa/pull/1447), which adds a 'preferredLocale' cookie, whenever the language is changed. This cookie is then considered everytime the PWA reloads. This will solve this issue too. But be aware that there are still some problems, why the PR is not yet merged.
