### ISSUE TITLE
Loading animation is not shown on scrollable pages

### ISSUE THREAD

**Issue by SGrueber** [intershop/intershop-pwa#166]
**Actual Behavior**
If a page has a height bigger than the screen like an order list with many entries the loading animation is not shown.

**Expected Behavior**
The loading animation is shown centered related to the screen.
 

**Steps to Reproduce the Bug**
1. Create 15 orders.
2. Go to myAccount/order history
3. The order list is greyed out during the data reload but the loading animation icon is not visible

**Comment by shauke** [comment]
While the current solution might solve the described issue it breaks the intended context sensitive loading animations e.g. for product tiles or endless scrolling. We only get ONE page centered animation that might tell us something on the page is still loading. The partial context where this happens is lost (see screenshots).
We will need to revert the current solution and come up with one that keeps the intended behavior and fixes the described problem more specific.

**Before the Fix**

![inTRONICS Home - Intershop PWA 4-17-2020 9-44-15 AM](https://user-images.githubusercontent.com/50741106/79557617-28c14200-80a3-11ea-8975-366e13dab622.png)

![inTRONICS Home - Intershop PWA 4-17-2020 9-46-16 AM](https://user-images.githubusercontent.com/50741106/79557652-3676c780-80a3-11ea-8f96-6d243bb375ed.png)


**After the Fix**

![inTRONICS Home - Intershop PWA 4-17-2020 9-41-58 AM](https://user-images.githubusercontent.com/50741106/79557714-4ee6e200-80a3-11ea-980f-9ab440c22545.png)

![inTRONICS Home - Intershop PWA 4-17-2020 9-47-47 AM](https://user-images.githubusercontent.com/50741106/79557735-573f1d00-80a3-11ea-9c67-cca42d3a8b36.png)

**Comment by shauke** [comment]
Since no easy solution could be found for this problem that would keep the initial intended loading functionality while fixing the loading spinner being out of the view port for some special cases it was decided to leave it the way it is for now.

Using with `background-attachment: fixed;` with the `.loading {}` CSS definition for some cases might be a path to explore further if needed. But this should somehow only be applied for the special cases since in most other cases the current behavior is the wanted one.
