### ISSUE TITLE
Question about wishlist structure

### ISSUE THREAD

**Issue by iznogood112** [intershop/intershop-pwa#364]
I was wondering why the "preferred" field is only returned in the wishlist detail call and not in the overview?
This results in the need to get all the wishlist for a customers profile just to know which one is the preferred one.

Overview response:
{
	"elements": [{
		"type": "Link",
		"uri": "inSPIRED-inTRONICS-Site/-;loc=en_US;cur=USD/customers/-/wishlists/fw8KCgoEzAMAAAF0gH4GFSTt",
		"title": "Test",
		"itemId": "fw8KCgoEzAMAAAF0gH4GFSTt"
	}, {
		"type": "Link",
		"uri": "inSPIRED-inTRONICS-Site/-;loc=en_US;cur=USD/customers/-/wishlists/HYMKCgoEt_QAAAF04pIGFSTt",
		"title": "Test 2",
		"itemId": "HYMKCgoEt_QAAAF04pIGFSTt"
	}],
	"type": "ResourceCollection",
	"name": "wishlists"
}

Detail response:
creationDate: 1598347378304
itemsCount: 0
preferred: true
public: false
title: "Test"
type: "WishList"

We would like to have the preferred field in the overview response.

**Comment by shauke** [comment]
Unfortunately this is a known limitation of the ICM wishlist REST API. We cannot change that in the context of this PWA REST client.
But I opened an internal Jira ticket (for reference IS-30762) for the ICM development that addresses this shortcoming and I hope that it might be changed in a future ICM version.
In any way, since we show more than the wishlist name (e.g. the items) in our PWA wishlists overview we need to fetch all wishlists details anyways. So there would be even more to wish for from the listing call.
