### ISSUE TITLE
trademark violation

### ISSUE THREAD

**Issue by philkunz** [intershop/intershop-pwa#39]
You guys are using trademarked logos of companies and putting those under MIT license in your repository. You can't do that ! Please clean your repository history. See examples here https://github.com/intershop/intershop-pwa/blob/develop/src/assets/mock-img/brands

Note: I'm writing this issue unrelated to any projects I'm working on.

**Comment by philkunz** [comment]
Also I find that parts of the reference design and name look close to https://intronics.nl

Since they are using Intershop, yet not using this repository as base, from what I can see, I have a few questions as result:

1. Could you elaborate how the two (the intronics.nl website and this repo) fit together? Their theme reveals a lot of classes I can attribute to intronics, but not yet to Intershop. Do both use the same Open Source reference design maybe?

1. Are there are any copyright or trademark issues here in your opinion? Or is it safe to use this repository as a base for integration of Intershop software in that regard?

**Comment by rkarl-ish** [comment]
Hi Phil,
thank you for bringing up this topic. Of course we do not intend to violate any ip rights within our project. We will replace the mentioned trademarked logos immediately. They are used as as mock data only anyways.

For the relation of this repo to intronics.nl, they are not related. We use this name as part of our demo data, a fictional company named "inSPIRED" with different shops for different industries, "inTRONICS" for consumer electronics, "inSPORTS" for sports fashion and inTOOLS for a b2b shop selling tools. The "in" stands for Intershop and is part of our marketing story.

When the respective team created the demo scenario several years ago it was not aware that a company intronics existed and was even a customer of ours. We later figured out and agreed that we can use this name within our demo scenario. However as we are now an open source project, we will again get in contact and clarify how to handle the situation moving forward.

**Comment by shauke** [comment]
@philkunz Thank you for pointing out the trademark issues in our project.

As a result we removed the referenced content and any other questionable content we could find from the complete GitHub repository. In addition we changed our demo scenario that is supposed to give a first impression even without a connected Intershop Commerce Management server in a way that does not rely on the removed content.

The new hotfix release 0.16.1 represents now the new cleaned working state of our project.
Older releases might have problems with missing assets because of the repository cleanup.
