### ISSUE TITLE
appRef.isStable inside cookies.service.ts not true

### ISSUE THREAD

**Issue by nickyhaze-incentro** [intershop/intershop-pwa#444]
When we look at the cookiebar service we see that the appRef.isStable observable is not becoming true inside the cookies.service.ts. Because of this the gtm script is not injected in the html from the tracking.module.ts.

Would be great if you can tell us why this isStable is not becoming true.

**Comment by shauke** [comment]
With the replacement of the ngx-cookie-banner with our own more granular and configurable cookie consent implementation the `cookieLawSeen$` ReplaySubject is gone and with that the need for the `appRef.isStable` check. So with version 0.25.0 of the PWA the issue within the CookiesService should be gone.

In any way you might need to check your PWA project for causes of `appRef.isStable` not becoming `true` (see https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/angular-change-detection.md) since the Tracking Script initialization does work with the standard PWA project, as can be seen on our demo server (https://intershoppwa.azurewebsites.net/home).
