### ISSUE TITLE
throttleOnBrowser() not working as expected on products effects when with SSR

### ISSUE THREAD

**Issue by anumang** [intershop/intershop-pwa#471]
**Actual Behavior**
Browser throttle one one of the critical behaviour when concerning SSR performance but this approach is not working as expected by using function `throttleOnBrowser ()` with `map(identity)`;

https://github.com/intershop/intershop-pwa/blob/57bcabb70a3636f10631212fcc0dd41462a8b35f/src/app/core/store/shopping/products/products.effects.ts#L383-L385

**Expected Behavior**
It should be working as expected and provide correct throttling functionality with SSR

**Steps to Reproduce the Bug**

1. Open any product master variations page
2. Debug with dev tools to see 'Intershop-pwa-state' 
3. Check for any variation products within server state

**Environment Details**

- Desktop: \*

  - OS: macOS 10.15
  - Browser Safari 14
  - [0.25.0](https://github.com/intershop/intershop-pwa/releases/tag/0.25.0)

**Additional Context, like Screenshots, Log File Snippets etc.**

In my trials, stand alone `map(identity)` usage not working as expected but If I used with some delay before it, it worked as expected, such as;
`.pipe(delay(500), map(identity)` 
But for temporary solution, we used another common pattern

**Comment by dhhyi** [comment]
I'm not quite sure, I understand your expectations.
The method throttleOnBrowser throttles multiple invocations for the browser application. So if you are on the product detail page of product A and you also have product A in the basket, then both the page and the mini-basket will trigger actions to load product A. This shouldn't cause 2 identical calls on the browser side, that's why a throttleTime is introduced in the effect to cause only one API call.
As throttleTime also starts a micro-task timer, this will delay the server side rendering disregarding if the call actually happens multiple times or not, that's why throttleTime should not be used for the server side application.
A throttle is not a delay, maybe that's causing confusion.
The SSR process should prerender all variations on the master variation page, so they are also linked in the store. I don't see any problems here.

**Comment by anumang** [comment]
Hi @dhhyi , sorry for reflecting my wrong code reading, with a little suspicious look for identity function, I thought we don't need to render variation products with SSR hence it's chained network blocker with addition to master product call & paginated variation call. 

If you believe,

 "The SSR process should prerender all variations on the master variation page, so they are also linked in the store. I don't see any problems here.", 

I am requesting to **close this bug issue** which opened my misreading & understanding.

**Comment by dhhyi** [comment]
No problem 😉
