### ISSUE TITLE
[Bug] 0.16.0 missing assets

### ISSUE THREAD

**Issue by hebra** [intershop/intershop-pwa#54]
**Actual Behavior**
- the 0.16.0 release is missing many assets like the roboto fonts, favicon, sprite-icons.svg, logo.ong and the homepage refers to products which don't exist in the standard ICM demo store.

**Expected Behavior**
- at least all assets which are not retrieved via REST should be part of the distribution.
 **Will you handle the bug fix?**

[ ] Yes
[ X] No

**Comment by shauke** [comment]
Because of trademark issues in our Open Source project (see #39) we had to clean the GitHub repository and remove questionable content. This results in missing assets in all previous releases. These issues cannot be fixed. The solution is to work with the new release 0.16.1 or any of the following releases. Also the current 'develop' branch contains an "out of the box" working state.
