### ISSUE TITLE
MockComponent is deprecated but advised, should advise mockComponents

### ISSUE THREAD

**Issue by ismail-codinglab** [intershop/intershop-pwa#546]
I am writing tests in PWA intershop, in the lint rules it is advising to use mockcompont instead of mockcomponents, why is that?

![image](https://user-images.githubusercontent.com/48755937/107783775-e8763300-6d4a-11eb-9e94-bef5c50de8ef.png)

MockComponent is deprecated and advised to use MockComponents by the ng-mocks devs. 

tslint.json:
```
        {
          "import": "^MockComponents$",
          "from": "ng-mocks",
          "filePattern": "^.*\\.spec\\.ts*$",
          "message": "Use MockComponent for individual components in tests instead."
        },
```

**Action**
Either advise MockComponents since `mockComponent` is deprecated or remove this tslint rule.

**Comment by dhhyi** [comment]
Hi @ismail-codinglab,

you are misreading something there. It's only the signature using `metaData` that's being deprecated, the normal call with just the component type stays supported. As far as I can see, we never used the `metaData` in the PWA.
The current version of the PWA uses Version 11 of ng-mocks and runs just fine.

The reason we are preferring `MockComponent` instead of `MockComponents` is that we have a tslint rule sorting all the `declarations` in the TestBed and it currently does not support sorting deep parameters.
