### ISSUE TITLE
[Bug] Merging 0.16.1 as 2nd upstream repository: "refusing to merge unrelated histories"

### ISSUE THREAD

**Issue by 127001** [intershop/intershop-pwa#62]
**Actual Behavior**
$ git merge intershop/master
fatal: refusing to merge unrelated histories

**Expected Behavior**
$ git merge intershop/master
Start a merge and inform me of the issues I need to resolve manually.

**Steps to Reproduce the Bug**
Until 0.15 it was possible to merge the latest changes into our current project using the documentation "[Keeping Custom Project up to Date](https://support.intershop.com/kb/index.php/Display/2928M0#Guide-IntershopProgressiveWebApp0.15-KeepingCustomProjectuptoDate)" using the zip-release from the intershop repository. Version 0.16(.1) is not available there. The new source is github.

As of 0.16, this section in the [documentation](https://support.intershop.com/kb/index.php/Display/2930D1#Guide-IntershopProgressiveWebApp0.16-DevelopmentProject) has been removed.

$ cd to-your-project-directory
$ git remote add intershop git@github.com:intershop/intershop-pwa.git
$ git fetch --all
$ git merge intershop/master

**Environment Details**
Custom project based of Intershop PWA 0.14, with 0.15 merged into our code base.

**Comment by dhhyi** [comment]
Yes, we have pushed a different history of the project into GitHub.

The history from the zipped repository was a partially squashed version of our internal git repository. By going open source, we decided to push the more detailed version of our internal development to GitHub as it helps identifying issues more clearly if you have deeper insights into the developing process.

You should still be able to start a merge if you add the `--allow-unrelated-histories` flag. Can you please try and give feedback?

**Comment by 127001** [comment]
Yes, tried that. The diff becomes so big that IntelliJ can't handle the conflicts anymore:

[gitmergenohistory.txt](https://github.com/intershop/intershop-pwa/files/3968173/gitmergenohistory.txt)

**Comment by 127001** [comment]
But if this is the way, then I guess I'll have to go through the many conflicts manually.

**Comment by dhhyi** [comment]
We are not out of options, yet. There are many merge strategies. :grin: Can you also try adding ` -s subtree` and see the result?

I can currently only test this on a vanilla zipped git repo vs. the GitHub branches. This merge strategy just ran right through.

**Comment by 127001** [comment]
Not sure if I use the command correctly:
$ git merge intershop/master -s subtree --allow-unrelated-histories

If I do this, about all our custom code is removed. 

[gitmerge-subtree.txt](https://github.com/intershop/intershop-pwa/files/3969892/gitmerge-subtree.txt)

**Comment by dhhyi** [comment]
Okay. It seems like there is no easy way of doing this. Let's evaluate some approaches:

#### Merging
If you merge the new history into your old history, you are basically importing the complete history since the beginning of time, because both repositories don't have a common ancestor. As you see, you get a lot of merge conflicts, that have to be resolved manually.

#### Patching the customization onto the new history
You could also calculate a diff of your current work against the 0.15 Release and apply this patch onto the new repository, hereby losing access to your history as you just import it completely with one commit (or more if you split it). This way however you'll get the advantage of a common history again.

#### Cherry Picking onto your history
You can also cherry-pick all commits from the 0.15.0 until 0.16.1 into your current history. You will have the opportunity to skip commits, that you don't need, but you will have to go through a lot of commits. This way you will not have a common history afterwards and you probably will always have to import changes that way.

So, choose wisely. :sweat_smile:

**Comment by 127001** [comment]
:-(

We already started with two team members on trying the patching some sort of cherry picking.

**Comment by nickyhaze** [comment]
We have done the following to merge the 0.16.1 in our project.

1. Added the 'https://github.com/intershop/intershop-pwa.git' as a remote.
2. Checkout a feature branch based on your Intershop master branch (0.16.1)
3. Pulled our develop branch inside this created feature branch, but with the '--allow-unrelated-histories' flag
4. fixed all merge conflicts and errors.

**Comment by 127001** [comment]
For us, this workaround solves the merge issue. But everyone who started with developing prior to open sourcing the PWA will experience the same issue. I think it is wise to add some information in the [0.16 PWA Guide](https://support.intershop.com/kb/index.php/Display/2930D1#Guide-IntershopProgressiveWebApp0.16-DevelopmentProject) and beyond to warn developers. Simply removing the upgrade information isn't good enough.

And perhaps also in [CUSTOMIZING.md](https://github.com/intershop/intershop-pwa/blob/develop/CUSTOMIZING.md).

**Comment by 127001** [comment]
I'm closing this issue. For us, the issue was solved by cherry picking our code on top of the new intershop-pwa history.

**Comment by dhhyi** [comment]
> I'm closing this issue. For us, the issue was solved by cherry picking our code on top of the new intershop-pwa history.

This sounds a lot like the rebase strategy which will also be in the documentation later on: https://github.com/intershop/intershop-pwa/pull/77/files.

Thank you for all the input. :+1:
