### ISSUE TITLE
How to run Cypress headless & other questions.

### ISSUE THREAD

**Issue by ismail-codinglab** [intershop/intershop-pwa#706]
I am not sure where I should go for intershop related technical questions so i'm sorry in advance if this is the wrong place.

### Q1. How can i run cypress headless?
Knowing there is a custom implementation with `node open-cypress`
Is there a `node run-cypress` equivalent?

I know there is `cypress run --headless` but not sure if this breaks intershop's custom code

### Q2. Why is there a custom implementation of cypress?
Why not utilize their architecture and implement it as a plugin instead of a plain script.

### Q3. More related to components. Some components dont have a component.css, why not?
Currently we are running into issues of deadcode, mixed styling and not knowing where the styling is for a specific component.

**Comment by dhhyi** [comment]
Hi @ismail-codinglab,

As you can see in the script itself (https://github.com/intershop/intershop-pwa/blob/develop/e2e/open-cypress.js) it does nothing more than figure out the value for the environment variable `ICM_BASE_URL`.
Our cypress tests need the ICM backend URL, because some of them are creating users and baskets for testing via REST API and hereby speed-up the testing.
You can skip this step entirely and rely on the standard CLI for cypress as long as you properly set the `ICM_BASE_URL` yourself. Nothing should break, everything should be working.

Running cypress with `--headless` might not be what you want if Electron is chosen as the browser. Some of the tests will fail if you do. Consider setting up a proper environment with Xvfb.

This should answer Q1 and Q2, right?

**Comment by shauke** [comment]
Hi @ismail-codinglab,

regarding question Q3 "Some components don't have a component.css, why not?"
I would say the question is more "Why do almost all components not have a *.component.scss?" There are currently only 7 components with component styles out of over 300 components.

So basically all styling in the Intershop PWA is coming from the global styles in the SCSS files in the `/src/styles` folder plus the imported styles of Bootstrap, Font Awesome, Toastr and Swiper (see https://github.com/intershop/intershop-pwa/blob/develop/src/styles/main.scss).

There are currently two reasons why we are using global styles instead of component styles.
The main reason is documented [here ](https://github.com/intershop/intershop-pwa/blob/develop/docs/concepts/styling-behavior.md) stating 

> The visual design (styling) [...] of the Intershop Progressive Web App is derived from the Responsive Starter Store [Intershops classic HTML based storefront] [...].

So this was a basic decision at the beginning of the Intershop PWA project to inherit the styling of our previous storefront and with that the implementation as a global styling. Something we and our customers and partners were used to and something that still works without any issue in a Single Page Application based on the Angular framework.
During our work on the PWA we also got to know component styling better and some of their advantages and disadvantages but up til now we did not do a general rethinking and rework of our styling approach.

A second reason (that came into the project during development), that makes it harder now to work more with component styles, is our theming concept. The dynamic approach of being able to switch our storefront theme based on a PWA run configuration makes it currently impossible to work with global SCSS variables in component styles. The inability to use global variables like `$space-default` or colors or fonts is very limiting to the component styling and therefore we did not use it more up til now.

We are currently thinking about changing our theming approach and with that also the component styling will get more focus but we are not there yet. I hope this answers all your current questions?
