### ISSUE TITLE
Unlimited budget - Undefined and N/A is displayed in buyer approval box

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#951]
**Actual Behavior**
If budget is set to unlimited, undefined already spent, N/A remaining budget, N/A including this order is displayed.

**Expected Behavior**
If budget is set to unlimited, hide already spent in %, remaining budget and including this order in %.

We hide the already spent completely in dashboard and user management. I would like to make this consistent. Please add already spent (in $) in the dashboard widget and user management list. It should look like a defined budget but without the progress bar.

**Steps to Reproduce the Bug**

1. Create a new user with unlimited budget
2. Place a requisition with this user
3. See approval/requisition details

**Environment Details**

  - Browser: Chrome [e.g. chrome, safari], Version [e.g. 22]
  - Project Code Version: Public Demo Server 1.3

**Additional Context, like Screenshots, Log File Snippets etc.**

Unlimited order spend limit and unlimited budget:
<img width="435" alt="2021-12-01 13_40_15-My Account _ Intershop PWA" src="https://user-images.githubusercontent.com/66066967/145051518-cf34b4ea-bb41-48ea-b2ef-0206ab42a020.png">

Only unlimited budget:
<img width="438" alt="2021-12-01 13_45_19-My Account _ Intershop PWA" src="https://user-images.githubusercontent.com/66066967/145051483-250bcb9b-6509-499b-96ed-e6fa477a463b.png">

[AB#71926](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71926)

**Comment by SGrueber** [comment]
In case a user has an unlimited budget the REST response doesn't return the data for alreadySpent. That's why it isn't possible to add the alreadySpent on the dashboard widget and user list.
The buyer approval widget has been enhanced, the percentage values and the remaining budget are not shown if there is no budget. But this feature is not working as expected, anyway so it is not worth improving it furthermore.
